import { loadTokens, sleep } from "./lib/env.mjs";
import { launchBrowser } from "./lib/browser.mjs";
import { createChannel, deleteChannel, joinChannel, sendMessage } from "./lib/api.mjs";
const { admin, b } = await loadTokens();
const c = await createChannel(admin.token, { name: "E2E dbg " + Date.now(), isPrivate: false });
const id = Number(c.json.data.id);
await joinChannel(b.token, id);
const br = await launchBrowser({ label: "B" });
await br.loginWithRememberToken(b.remember);
await br.goto("/chat/c/" + id);
await sleep(4000);
await br.evaluate(`window.__ev=[]; app.websocket_channels.user.bind_global((e,d)=>window.__ev.push(e)); true`);
const t0=Date.now();
console.log((await sendMessage(admin.token, id, "hello-dbg")).status);
await sleep(3000);
console.log(await br.evaluate(`JSON.stringify({ev:window.__ev, active: flarum.extensions['ramon-chat'] && null, txt:(document.querySelector('.ChatChannel-stream')?.textContent||'').slice(-200), n: document.querySelectorAll('.ChatChannel-stream').length, hidden: document.hidden})`));
console.log(br.requests.filter(r=>r.at>t0 && r.url.includes('/api/')).map(r=>r.method+' '+r.url.replace(/^.*\/api/,'')).join('\n'));
await br.evaluate("app.websocket.disconnect(), true");
const t1=Date.now();
await sleep(5000);
console.log(await br.evaluate(`JSON.stringify({state: app.websocket.connection.state, hidden: document.hidden})`));
console.log('after drop', br.requests.filter(r=>r.at>t1).map(r=>r.method+' '+r.url.replace(/^.*\/api/,'')).join('\n'));
await br.close(); await deleteChannel(admin.token,id); process.exit(0);
