<?php

/*
 * This file is part of ramon/chat.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ramon\Chat;

use Carbon\Carbon;
use Flarum\Database\AbstractModel;
use Flarum\Database\ScopeVisibilityTrait;
use Flarum\Formatter\Formattable;
use Flarum\Formatter\HasFormattedContent;
use Flarum\Foundation\EventGeneratorTrait;
use Flarum\User\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Query\Expression;

/**
 * @property int $id
 * @property int $channel_id
 * @property int|null $user_id
 * @property int|null $thread_id
 * @property int|null $number
 * @property int|null $reply_to_id
 * @property string|null $content
 * @property string|null $parsed_content
 * @property string $type
 * @property string|null $system_key
 * @property array|null $system_data
 * @property int|null $webhook_id
 * @property Carbon|null $edited_at
 * @property int|null $edited_by_id
 * @property Carbon|null $deleted_at
 * @property int|null $deleted_by_id
 * @property Carbon|null $pinned_at
 * @property int|null $pinned_by_id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property-read Channel|null $channel
 * @property-read User|null $user
 * @property-read Thread|null $thread
 * @property-read Message|null $replyTo
 * @property-read Collection<int, MessageReaction> $reactions
 * @property-read Collection<int, Upload> $uploads
 * @property-read Collection<int, MessageMention> $mentions
 * @property-read Collection<int, MessageRevision> $revisions
 */
class Message extends AbstractModel implements Formattable
{
    use EventGeneratorTrait;
    use ScopeVisibilityTrait;
    use HasFormattedContent;

    public const TYPE_TEXT = 'text';

    /**
     * Generated by the system rather than a user — joins, leaves, channel status
     * changes. Rendered from a locale key, never from user prose.
     */
    public const TYPE_SYSTEM = 'system';

    /**
     * Posted by the chat's own bot rather than by a person.
     *
     * Distinct from TYPE_SYSTEM: a system message is grey narration rendered from a
     * locale key, while a bot message is an ordinary message that happens to have no
     * human author — real content, real formatting, real position in the stream. It
     * carries `user_id = null`, and the client draws the name and avatar from the
     * admin's settings, so no account has to exist for the bot and none can be
     * logged into or impersonated.
     */
    public const TYPE_BOT = 'bot';

    protected $table = 'chat_messages';

    public $timestamps = true;


    protected $casts = [
        'channel_id'     => 'integer',
        'user_id'        => 'integer',
        'thread_id'      => 'integer',
        'number'         => 'integer',
        'reply_to_id'    => 'integer',
        'webhook_id'     => 'integer',
        'edited_by_id'   => 'integer',
        'deleted_by_id'  => 'integer',
        'pinned_by_id'   => 'integer',
        'system_data'    => 'array',
        'edited_at'      => 'datetime',
        'deleted_at'     => 'datetime',
        'pinned_at'      => 'datetime',
    ];

    public static function boot(): void
    {
        parent::boot();

        // Assign the per-channel sequence at insert time using a subquery so
        // concurrent sends cannot both read the same max and collide on the
        // (channel_id, number) unique index.
        static::creating(function (self $message) {
            if ($message->number === null && $message->channel_id !== null) {
                $db = static::getConnectionResolver()->connection();
                $prefix = $db->getTablePrefix();

                // Raw, and it has to be. The SQL is embedded in an Expression so
                // that the whole subquery lands inside the INSERT — and an
                // Expression carries no bindings, so `toSql()` would emit a bare
                // `?` with nothing to fill it. The two interpolations are
                // therefore inlined deliberately, and neither can carry input:
                // the channel id is cast to int, and the prefix comes from the
                // connection's own config, never from a request.
                $message->number = new Expression('('.
                    $db->table('chat_messages', 'cm')
                        // nosemgrep: github.semgrep.flarum-v2-raw-sql-concat
                        ->whereRaw($prefix.'cm.channel_id = '.(int) $message->channel_id)
                        // nosemgrep: github.semgrep.flarum-v2-raw-sql-concat
                        ->selectRaw('COALESCE(MAX('.$prefix.'cm.number), 0) + 1')
                        ->toSql()
                    .')');
            }
        });

        // The Expression above survives on the in-memory model after insert, so
        // the resolved value has to be read back or every caller sees a stale
        // `number`.
        //
        // The check must look at the *raw* attribute, not `$message->number`:
        // the `integer` cast runs on the way out and casting an Expression object
        // to int yields 1, which both hides the object and makes an
        // `instanceof` test on the accessor always false. That combination
        // silently reported number=1 for every message.
        static::created(function (self $message) {
            $raw = $message->getAttributes()['number'] ?? null;

            if ($raw instanceof Expression) {
                $message->number = (int) static::getConnectionResolver()
                    ->connection()
                    ->table('chat_messages')
                    ->where('id', $message->id)
                    ->value('number');

                $message->syncOriginalAttribute('number');
            }
        });
    }

    public static function build(
        Channel $channel,
        ?User $user,
        string $content,
        ?Thread $thread = null,
        ?Message $replyTo = null
    ): static {
        $message = new static();

        $message->channel_id = $channel->id;
        $message->user_id = $user?->id;
        $message->thread_id = $thread?->id;
        $message->reply_to_id = $replyTo?->id;
        $message->type = self::TYPE_TEXT;
        $message->created_at = Carbon::now();

        // Assigned via the mutator so the formatter parses it with the author as
        // the acting user (mentions, permissions inside the formatter pipeline).
        $message->setContentAttribute($content, $user);

        return $message;
    }

    public static function buildSystem(Channel $channel, string $key, array $data = []): static
    {
        $message = new static();

        $message->channel_id = $channel->id;
        $message->type = self::TYPE_SYSTEM;
        $message->system_key = $key;
        $message->system_data = $data;
        $message->created_at = Carbon::now();

        return $message;
    }

    /**
     * A message the chat itself posts — an ordinary message with no human author.
     *
     * Content goes through the same formatter as anyone else's, so links, emphasis
     * and mentions render identically; the only difference is that the author is
     * drawn from settings instead of a user record.
     *
     * `$actor` is who the formatter parses as. Passing null means the content is
     * parsed as a guest would write it, which is deliberate: the bot must not
     * inherit a member's permissions inside the formatter pipeline just because
     * their action is what triggered the post.
     *
     * @param  array<string, mixed>  $data  Structured detail kept alongside the
     *                                      prose, so the message stays queryable
     *                                      and a future renderer is not left
     *                                      parsing its own output back.
     */
    public static function buildBot(Channel $channel, string $key, string $content, array $data = []): static
    {
        $message = new static();

        $message->channel_id = $channel->id;
        $message->user_id = null;
        $message->type = self::TYPE_BOT;
        $message->system_key = $key;
        $message->system_data = $data;
        $message->created_at = Carbon::now();

        $message->setContentAttribute($content, null);

        return $message;
    }

    public function isBot(): bool
    {
        return $this->type === self::TYPE_BOT;
    }

    public function isSystem(): bool
    {
        return $this->type === self::TYPE_SYSTEM;
    }

    public function isDeleted(): bool
    {
        return $this->deleted_at !== null;
    }

    /**
     * `pinned_at` alone decides this; `pinned_by_id` is attribution and is nulled
     * together with it, so the two can never disagree.
     */
    public function isPinned(): bool
    {
        return $this->pinned_at !== null;
    }

    public function isEdited(): bool
    {
        return $this->edited_at !== null;
    }

    public function isInThread(): bool
    {
        return $this->thread_id !== null;
    }

    /**
     * True when this message is the message a thread hangs off.
     */
    public function isThreadRoot(): bool
    {
        return $this->thread_id !== null
            && $this->thread !== null
            && $this->thread->original_message_id === $this->id;
    }

    public function channel(): BelongsTo
    {
        return $this->belongsTo(Channel::class, 'channel_id');
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function editedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'edited_by_id');
    }

    public function deletedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'deleted_by_id');
    }

    public function pinnedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'pinned_by_id');
    }

    public function thread(): BelongsTo
    {
        return $this->belongsTo(Thread::class, 'thread_id');
    }

    public function replyTo(): BelongsTo
    {
        return $this->belongsTo(self::class, 'reply_to_id');
    }

    public function webhook(): BelongsTo
    {
        return $this->belongsTo(Webhook::class, 'webhook_id');
    }

    public function reactions(): HasMany
    {
        return $this->hasMany(MessageReaction::class, 'message_id');
    }

    public function uploads(): HasMany
    {
        return $this->hasMany(Upload::class, 'message_id');
    }

    public function mentions(): HasMany
    {
        return $this->hasMany(MessageMention::class, 'message_id');
    }

    public function revisions(): HasMany
    {
        return $this->hasMany(MessageRevision::class, 'message_id');
    }

    public function bookmarks(): HasMany
    {
        return $this->hasMany(Bookmark::class, 'message_id');
    }

    public function flags(): HasMany
    {
        return $this->hasMany(MessageFlag::class, 'message_id');
    }

    /**
     * Records the pre-edit content so the edit history stays reconstructable,
     * then applies the new content.
     */
    public function reviseContent(string $content, User $actor): static
    {
        $previous = $this->attributes['content'] ?? null;

        if ($previous !== null) {
            $revision = new MessageRevision();
            $revision->message_id = $this->id;
            $revision->setParsedContentAttribute($previous);
            $revision->edited_by_id = $actor->id;
            $revision->created_at = Carbon::now();
            $revision->save();
        }

        $this->setContentAttribute($content, $this->user ?? $actor);
        $this->edited_at = Carbon::now();
        $this->edited_by_id = $actor->id;

        return $this;
    }
}
